name: axe
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  axe:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup node - Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install dependencies
      run: npm ci
    
    - name: Fetch latest content from Storyblok
      run: |
        node fetch-storyblok-content.js
  
    - name: Build
      run: npm run build --if-present

    - run: npm start & npx wait-on http://localhost:3000
    - name: Run axe
      run: |
        npm install -g @axe-core/cli -g
        axe http://localhost:3000 --exit